//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KayitTutma
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KayitDBEntities : DbContext
    {
        public KayitDBEntities()
            : base("name=KayitDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Senetler> Senetler { get; set; }
        public virtual DbSet<Vadeler> Vadeler { get; set; }
        public virtual DbSet<OdemeGecmisi> OdemeGecmisi { get; set; }
    }
}
