//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KayitTutma
{
    using System;
    using System.Collections.Generic;
    
    public partial class OdemeGecmisi
    {
        public int id { get; set; }
        public int senetID { get; set; }
        public int Vade { get; set; }
        public System.DateTime OdemeTarihi { get; set; }
    }
}
