//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KayitTutma
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vadeler
    {
        public int id { get; set; }
        public int senetID { get; set; }
        public System.DateTime Tarih { get; set; }
        public decimal Tutar { get; set; }
        public int VadeNo { get; set; }
    
        public virtual Senetler Senetler { get; set; }
    }
}
